version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout 
      - run:
          command: |
            sudo pip install pytest pytest-cov coveralls
      - run:
          command: |
            coverage run --source easy_exceptions -m pytest tests/ && coverage html
      - run:
          command: |
            coveralls
      - store_artifacts:
          path: htmlcov
