version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout 
      - run:
          command: |
            sudo pip install pytest pytest-cov python-coveralls
      - run:
          command: |
            pytest --cov-report html --cov-report term-missing --cov=easy_exceptions/ tests/ 
      - run:
          command: |
            coveralls
      - store_artifacts:
          path: htmlcov
